vim.cmd("set relativenumber")        
vim.cmd("set shiftwidth=4")
vim.cmd("set mouse=v")
vim.cmd("syntax on")
vim.cmd("set nocompatible")          
vim.cmd("set showmatch")             
vim.cmd("set ignorecase")            
vim.cmd("set mouse=v")               
vim.cmd("set hlsearch")              
vim.cmd("set incsearch")             
vim.cmd("set tabstop=2")             
vim.cmd("set softtabstop=4")         
vim.cmd("set expandtab")             
vim.cmd("set shiftwidth=2")          
vim.cmd("set autoindent")            
vim.cmd("set number")                
vim.cmd("filetype plugin indent on")
vim.cmd("syntax on")               
vim.cmd("set mouse=a")               
vim.cmd("set clipboard=unnamedplus")
vim.cmd("filetype plugin on")
vim.cmd("set cursorline")            
vim.cmd("set ttyfast")               
vim.cmd("set backupdir=~/.cache/vim")
