require("plugins.nvim-tree-settings")
require("plugins.telescope-settings")
require("plugins.fugitive-settings")
require("plugins.treesitter-settings")
require("plugins.undotree-settings")
require("plugins.harpoon-settings")
require("plugins.render-markdown-settings")
require("plugins.lsp-config")
